--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/ImJustNozell/NzCrates
build-by-default: true
branches:
  - main
projects:
  NzCrates:
    path: ""
    icon: "icon.gif"
    lint:
      phpstan: false
    libs:
      - src: Muqsit/invmenu/InvMenu
        version: ^4.6
      - src: nozell/formsui/FormsUI
        version: ^1.0
