--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/ImJustNozell/NzCrates
build-by-default: true
branches:
  - main
projects:
  NzCrates:
    path: ""
    icon: "asesst/icon.gif"
    lint:
      phpstan: false
    libs:
      - src: Vecnavium/FormsUI/libFormsUI
        version: 1.1.3
...
