# Floating Texts for Crates / Textos Flotantes para Crates
#hablas español?
# tacha con "#" la versión ingles y quita el "#" de la versión en español

magefloatingtext: "§l§bMageCrate\n§eVenture into magic!"
# magefloatingtext: "§l§bMageCrate\n§e¡Aventúrate en la magia!"

icefloatingtext: "§l§bIceCrate\n§eExplore the frozen tundra!"
# icefloatingtext: "§l§bIceCrate\n§e¡Explora la fría tundra!"

enderfloatingtext: "§l§bEnderCrate\n§eUnleash the power of the End!"
# enderfloatingtext: "§l§bEnderCrate\n§e¡Desata el poder del End!"

magmafloatingtext: "§l§bMagmaCrate\n§eFeel the heat of magma!"
# magmafloatingtext: "§l§bMagmaCrate\n§e¡Siente el calor del magma!"

pegasusfloatingtext: "§l§bPegasusCrate\n§eSoar high with Pegasus!"
# pegasusfloatingtext: "§l§bPegasusCrate\n§e¡Vuela alto con Pegasus!"

# Won Item Messages / Mensajes de Ítem Ganado

won_item: "&e{userName} &aCongratulations! You have won&e {itemName}"
# won_item: "&e{userName} &a¡Felicidades! Has ganado&e {itemName}"

won_alert: "&6{userName} &ahas won an item&7:&e {itemName} &ain the crate&7:&e {crateName}."
# won_alert: "&6{userName} &aha ganado un ítem&7:&e {itemName} &aen la crate&7:&e {crateName}."
